spring:
    jackson:
        date-format: yyyy-MM-dd
#        serialization:
#            write-dates-as-timestamps: false
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${spring.datasource.database.host}:${spring.datasource.database.port}/${spring.datasource.database.name}
        password: postgres
        username: postgres
        database:
            host: localhost
            port: 5432
            name: medialine
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update

format:
    dateFormat: "yyyy-MM-dd"

security:
    whitelist:
        - "/api/admin/login"
        - "/api/feedback"
    authOnly:
        - "/api/admin/**"

cors:
    allowedOrigin: "http://localhost:4200"
    allowedHeader: "*"
    allowedMethod: "*"
    configurationPattern: "/**"



jwt:
    header: Authorization
    secret: secretmedialine123123123123123123123
    expiration: 86400

logging:
    level:
        root: INFO
        ru.medialine: DEBUG

server:
    port: 8080

resources:
    path: "/image/**"
#    relative to root project directory
    resourceLocation: "/uploads/"
    uploadPath: "./uploads/"

feedback:
    sender: "ap1kdungeonmaster2@gmail.com"
    subject: "Заявка формы обратной связи"
    receiver: "ApikMaster2@yandex.ru"
    templateParams:
      clientName: "clientName"
      clientPhone: "clientPhone"
    email-template-location: "emailTemplate.html"
    languages: "ru-RU"

email:
    host: "smtp.gmail.com"
    port: 587
    username: "ap1kdungeonmaster2@gmail.com"
    password: "qrry cwhy gxdi rsao"
    transport-protocol: "smtp"
    smtp-auth: true
    starttls-enable: true
    debug: true
