spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${spring.datasource.database.host}:${spring.datasource.database.port}/${spring.datasource.database.name}
        password: postgres
        username: postgres
        database:
            host: localhost
            port: 5432
            name: medialine
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
    #whiteip: http://localhost:4200
    whiteip: '*'
    port: 8080
    dateFormat: "yyyy-MM-dd"



security:
    whitelist:
        - "/api/admin/login"
    authOnly:
        - "/api/admin/**"

cors:
    allowedOrigin: "http://localhost:4200"
    allowedHeader: "*"
    allowedMethod: "*"
    configurationPattern: "/**"



jwt:
    header: Authorization
    secret: secretmedialine123123123123123123123
    expiration: 86400

logging:
    level:
        root: INFO
        ru.medialine: DEBUG

server:
    port: 8080